# Site settings
title: cron&#9398;rchy
header-img: cronarchy.com/img/cronarchy2.png
email: your-email@yourdomain.com
copyright_name: cron&#9398;rchy.com
description: "Rule By The Iron Fist Of Automation "
baseurl: "/"
url: "http://cronarchy.com"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia
email_username:  your-email@yourdomain.com

# Build settings
markdown: redcarpet
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
